<div class="bootcamp wrap">
    <div class="bootcamp__wrapper">
        <h1 class="wp-heading-inline">Quote list</h1>
        <a href="#"
           class="page-title-action">Add New</a>

        <hr class="wp-header-end" />

        <table class="widefat fixed">
            <thead>
                <tr>
                    <th class="column-columnname">#</th>
                    <th class="column-columnname">Author</th>
                    <th class="column-columnname">Quote</th>
                    <th class="column-columnname">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>James Bond</td>
                    <td>My name is James Bond</td>
                    <td>
                        <a href="#"><span class="dashicons dashicons-edit"></span>Edit</a>
                        &nbsp;
                        <a href="#"
                           onclick="return confirm('Are you sure you want to delete this quote?');">
                            <span class="dashicons dashicons-no-alt"></span>Delete
                        </a>
                    </td>
                </tr>
            </tbody>

        </table>
    </div>
</div>

