<div class="bootcamp wrap">
    <div class="bootcamp__wrapper">
        <h1 class="wp-heading-inline">Edit quote</h1>
        <hr class="wp-header-end" />

        <table class="widefat fixed">
            <tbody>
                <tr>
                    <td>
                        <label for="authorName">Author:</label>
                    </td>
                    <td>
                        <input name="authorName" id="authorName" type="text"/>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

